// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RustArchon.Api.Data;

#nullable disable

namespace RustArchon.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260907210543_PlanOnePerOwner")]
    partial class PlanOnePerOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JumpStart.Authorization.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Role_Name_WhereGlobal")
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex(new[] { "TenantId", "Name" }, "IX_Role_TenantId_Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("JumpStart.Authorization.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId", "Permission" }, "IX_RolePermission_RoleId_Permission")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("JumpStart.Authorization.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "UserId", "Permission", "TenantId" }, "IX_UserPermission_UserId_Permission_TenantId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("JumpStart.Authorization.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "UserId", "RoleId", "TenantId" }, "IX_UserRole_UserId_RoleId_TenantId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("JumpStart.Data.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsActive" }, "IX_Tenant_IsActive");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("JumpStart.Data.TenantInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TenantId", "Email");

                    b.ToTable("TenantInvitation");
                });

            modelBuilder.Entity("JumpStart.Data.UserTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "UserId", "IsActive" }, "IX_UserTenant_TenantId_UserId_IsActive");

                    b.HasIndex(new[] { "UserId", "IsActive" }, "IX_UserTenant_UserId_IsActive");

                    b.HasIndex(new[] { "UserId", "TenantId" }, "IX_UserTenant_UserId_TenantId")
                        .IsUnique();

                    b.ToTable("UserTenant");
                });

            modelBuilder.Entity("JumpStart.Forms.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowMultipleResponses")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("JumpStart.Forms.FormResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RespondentUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormResponses");
                });

            modelBuilder.Entity("JumpStart.Forms.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<string>("HelpText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("MaximumValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MinimumValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OptionValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormResponseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("FormResponseId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionResponses");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionResponseOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionResponseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionOptionId");

                    b.HasIndex("QuestionResponseId", "QuestionOptionId")
                        .IsUnique();

                    b.ToTable("QuestionResponseOptions");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowsMultipleValues")
                        .HasColumnType("boolean");

                    b.Property<string>("ApplicationData")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("HasOptions")
                        .HasColumnType("boolean");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayOrder");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AllowsMultipleValues = false,
                            ApplicationData = "{\"RazorComponentName\":\"ShortTextInput\"}",
                            Code = "ShortText",
                            Description = "Single line text input suitable for names, email, brief answers",
                            DisplayOrder = 1,
                            HasOptions = false,
                            InputType = "text",
                            Name = "Short Text"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AllowsMultipleValues = false,
                            ApplicationData = "{\"RazorComponentName\":\"LongTextInput\"}",
                            Code = "LongText",
                            Description = "Multi-line text area for longer responses, comments, descriptions",
                            DisplayOrder = 2,
                            HasOptions = false,
                            InputType = "textarea",
                            Name = "Long Text"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AllowsMultipleValues = false,
                            ApplicationData = "{\"RazorComponentName\":\"NumberInput\"}",
                            Code = "Number",
                            Description = "Numeric input for quantities, ratings, or numeric values",
                            DisplayOrder = 3,
                            HasOptions = false,
                            InputType = "number",
                            Name = "Number"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AllowsMultipleValues = false,
                            ApplicationData = "{\"RazorComponentName\":\"DateInput\"}",
                            Code = "Date",
                            Description = "Date picker for birth dates, appointments, event dates",
                            DisplayOrder = 4,
                            HasOptions = false,
                            InputType = "date",
                            Name = "Date"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AllowsMultipleValues = false,
                            ApplicationData = "{\"RazorComponentName\":\"BooleanInput\"}",
                            Code = "Boolean",
                            Description = "Binary choice with Yes/No or True/False radio buttons",
                            DisplayOrder = 5,
                            HasOptions = false,
                            InputType = "boolean",
                            Name = "Yes/No"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            AllowsMultipleValues = false,
                            ApplicationData = "{\"RazorComponentName\":\"SingleChoiceInput\"}",
                            Code = "SingleChoice",
                            Description = "Radio button list allowing one option to be selected",
                            DisplayOrder = 6,
                            HasOptions = true,
                            InputType = "radio",
                            Name = "Single Choice"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            AllowsMultipleValues = true,
                            ApplicationData = "{\"RazorComponentName\":\"MultipleChoiceInput\"}",
                            Code = "MultipleChoice",
                            Description = "Checkbox list allowing multiple options to be selected",
                            DisplayOrder = 7,
                            HasOptions = true,
                            InputType = "checkbox",
                            Name = "Multiple Choice"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            AllowsMultipleValues = false,
                            ApplicationData = "{\"RazorComponentName\":\"DropdownInput\"}",
                            Code = "Dropdown",
                            Description = "Dropdown/select list allowing one option to be selected",
                            DisplayOrder = 8,
                            HasOptions = true,
                            InputType = "select",
                            Name = "Dropdown"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            AllowsMultipleValues = true,
                            ApplicationData = "{\"RazorComponentName\":\"RankingInput\"}",
                            Code = "Ranking",
                            Description = "Drag-and-drop ranking list allowing users to order options by preference",
                            DisplayOrder = 9,
                            HasOptions = true,
                            InputType = "ranking",
                            Name = "Ranking"
                        });
                });

            modelBuilder.Entity("RustArchon.Api.Data.ConnectionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RustServerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "RustServerId", "OccurredAtUtc" }, "IX_ConnectionLogEntry_TenantId_RustServerId_OccurredAtUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("ConnectionLogEntry");
                });

            modelBuilder.Entity("RustArchon.Api.Data.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("AppliedToInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateTimeOffset>("IssuedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppliedToInvoiceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_CreditNote_TenantId");

                    b.ToTable("CreditNote");
                });

            modelBuilder.Entity("RustArchon.Api.Data.InvitationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoundEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RedeemedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedeemedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "IX_InvitationCode_Code")
                        .IsUnique();

                    b.ToTable("InvitationCode");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountCredited")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateTimeOffset?>("DueOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IssuedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProviderInvoiceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("VoidedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WrittenOffOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DueOn")
                        .HasDatabaseName("IX_Invoice_DueOn_WhereOpen")
                        .HasFilter("\"Status\" = 1");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Invoice_Number_WhereNumbered")
                        .HasFilter("\"Number\" IS NOT NULL");

                    b.HasIndex("TenantId", "DueOn")
                        .HasDatabaseName("IX_Invoice_TenantId_DueOn_WhereOpen")
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("RustArchon.Api.Data.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ServiceEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ServiceStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubscriptionPeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitAmount")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_InvoiceLine_InvoiceId");

                    b.HasIndex("SubscriptionPeriodId")
                        .HasDatabaseName("IX_InvoiceLine_SubscriptionPeriodId");

                    b.ToTable("InvoiceLine");
                });

            modelBuilder.Entity("RustArchon.Api.Data.InvoiceNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint");

                    b.Property<int>("PadWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_InvoiceNumberSequence_Scope");

                    b.ToTable("InvoiceNumberSequence");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReceivedOn")
                        .HasDatabaseName("IX_Payment_TenantId_ReceivedOn");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AllocatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReversedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_PaymentAllocation_InvoiceId");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_PaymentAllocation_PaymentId");

                    b.ToTable("PaymentAllocation");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasRoles")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaximumServers")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumUsers")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnePerOwner")
                        .HasColumnType("boolean");

                    b.Property<int>("PricingModel")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionHistory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Plan_Name_WhereActive")
                        .HasFilter("\"Active\"");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PlanPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<int>("IncludedUnits")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitAmount")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "TermMonths")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanPrice_PlanId_TermMonths");

                    b.ToTable("PlanPrice");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PlatformSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "IX_PlatformSetting_Key")
                        .IsUnique();

                    b.ToTable("PlatformSetting");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PlayerKillEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("KillerName")
                        .HasColumnType("text");

                    b.Property<string>("KillerSteamId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RustServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VictimName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VictimSteamId")
                        .HasColumnType("text");

                    b.Property<string>("Weapon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "RustServerId", "OccurredAtUtc" }, "IX_PlayerKillEvent_TenantId_RustServerId_OccurredAtUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("PlayerKillEvent");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PlayerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("GeolocationCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeolocationCountry")
                        .HasColumnType("text");

                    b.Property<string>("GeolocationCountryCode")
                        .HasColumnType("text");

                    b.Property<bool?>("GeolocationIsProxy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GeolocationIsVpn")
                        .HasColumnType("boolean");

                    b.Property<string>("GeolocationProvider")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LastPing")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LastViolationLevel")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RustServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SteamInfoCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SteamMinutesPlayedForever")
                        .HasColumnType("integer");

                    b.Property<int?>("SteamNumberOfGameBans")
                        .HasColumnType("integer");

                    b.Property<int?>("SteamNumberOfVacBans")
                        .HasColumnType("integer");

                    b.Property<bool?>("SteamVacBanned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "RustServerId", "ConnectedAtUtc" }, "IX_PlayerSession_TenantId_RustServerId_ConnectedAtUtc")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "TenantId", "RustServerId", "SteamId", "DisconnectedAtUtc" }, "IX_PlayerSession_TenantId_RustServerId_SteamId_DisconnectedAtUtc");

                    b.ToTable("PlayerSession");
                });

            modelBuilder.Entity("RustArchon.Api.Data.RconEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Identifier")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RustServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stacktrace")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "RustServerId", "CapturedAtUtc" }, "IX_RconEvent_TenantId_RustServerId_CapturedAtUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("RconEvent");
                });

            modelBuilder.Entity("RustArchon.Api.Data.RustServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedWorkerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectionStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ConnectionStatusChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectionStatusDetail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GeolocationApiKey")
                        .HasColumnType("text");

                    b.Property<int>("GeolocationProvider")
                        .HasColumnType("integer");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("RconPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteamApiKey")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "Name" }, "IX_RustServer_TenantId_Name")
                        .IsUnique();

                    b.ToTable("RustServer");
                });

            modelBuilder.Entity("RustArchon.Api.Data.ScheduledPlanChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("IX_ScheduledPlanChange_EffectiveDate_WherePending")
                        .HasFilter("\"AppliedOn\" IS NULL AND \"CancelledOn\" IS NULL");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_ScheduledPlanChange_TenantId_WherePending")
                        .HasFilter("\"AppliedOn\" IS NULL AND \"CancelledOn\" IS NULL");

                    b.ToTable("ScheduledPlanChange");
                });

            modelBuilder.Entity("RustArchon.Api.Data.ServerInfoSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Framerate")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("Memory")
                        .HasColumnType("integer");

                    b.Property<int>("NetworkIn")
                        .HasColumnType("integer");

                    b.Property<int>("NetworkOut")
                        .HasColumnType("integer");

                    b.Property<int>("Players")
                        .HasColumnType("integer");

                    b.Property<Guid>("RustServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "RustServerId", "CapturedAtUtc" }, "IX_ServerInfoSnapshot_TenantId_RustServerId_CapturedAtUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("ServerInfoSnapshot");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StatusChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Subscription_TenantId_WhereCurrent")
                        .HasFilter("\"EndDate\" IS NULL");

                    b.HasIndex("TenantId", "StartDate")
                        .HasDatabaseName("IX_Subscription_TenantId_StartDate");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("RustArchon.Api.Data.SubscriptionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EarnedAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "StartDate")
                        .HasDatabaseName("IX_SubscriptionPeriod_SubscriptionId_StartDate");

                    b.ToTable("SubscriptionPeriod");
                });

            modelBuilder.Entity("JumpStart.Authorization.Role", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JumpStart.Authorization.RolePermission", b =>
                {
                    b.HasOne("JumpStart.Authorization.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JumpStart.Authorization.UserPermission", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JumpStart.Authorization.UserRole", b =>
                {
                    b.HasOne("JumpStart.Authorization.Role", "Role")
                        .WithMany("UserAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JumpStart.Data.TenantInvitation", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JumpStart.Data.UserTenant", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany("UserTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JumpStart.Forms.FormResponse", b =>
                {
                    b.HasOne("JumpStart.Forms.Form", "Form")
                        .WithMany("Responses")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("JumpStart.Forms.Question", b =>
                {
                    b.HasOne("JumpStart.Forms.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JumpStart.Forms.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionOption", b =>
                {
                    b.HasOne("JumpStart.Forms.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionResponse", b =>
                {
                    b.HasOne("JumpStart.Forms.FormResponse", "FormResponse")
                        .WithMany("Answers")
                        .HasForeignKey("FormResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JumpStart.Forms.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormResponse");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionResponseOption", b =>
                {
                    b.HasOne("JumpStart.Forms.QuestionOption", "QuestionOption")
                        .WithMany("ResponseSelections")
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JumpStart.Forms.QuestionResponse", "QuestionResponse")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("QuestionResponseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionOption");

                    b.Navigation("QuestionResponse");
                });

            modelBuilder.Entity("RustArchon.Api.Data.ConnectionLogEntry", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.CreditNote", b =>
                {
                    b.HasOne("RustArchon.Api.Data.Invoice", "AppliedToInvoice")
                        .WithMany()
                        .HasForeignKey("AppliedToInvoiceId");

                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedToInvoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Invoice", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.InvoiceLine", b =>
                {
                    b.HasOne("RustArchon.Api.Data.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RustArchon.Api.Data.SubscriptionPeriod", "SubscriptionPeriod")
                        .WithMany()
                        .HasForeignKey("SubscriptionPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");

                    b.Navigation("SubscriptionPeriod");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Payment", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PaymentAllocation", b =>
                {
                    b.HasOne("RustArchon.Api.Data.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RustArchon.Api.Data.Payment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PlanPrice", b =>
                {
                    b.HasOne("RustArchon.Api.Data.Plan", "Plan")
                        .WithMany("Prices")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PlayerKillEvent", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.PlayerSession", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.RconEvent", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.RustServer", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.ScheduledPlanChange", b =>
                {
                    b.HasOne("RustArchon.Api.Data.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.ServerInfoSnapshot", b =>
                {
                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Subscription", b =>
                {
                    b.HasOne("RustArchon.Api.Data.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JumpStart.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RustArchon.Api.Data.SubscriptionPeriod", b =>
                {
                    b.HasOne("RustArchon.Api.Data.Subscription", "Subscription")
                        .WithMany("Periods")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("JumpStart.Authorization.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("JumpStart.Data.Tenant", b =>
                {
                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("JumpStart.Forms.Form", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("JumpStart.Forms.FormResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("JumpStart.Forms.Question", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionOption", b =>
                {
                    b.Navigation("ResponseSelections");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionResponse", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("JumpStart.Forms.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Payment", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Plan", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("RustArchon.Api.Data.Subscription", b =>
                {
                    b.Navigation("Periods");
                });
#pragma warning restore 612, 618
        }
    }
}
